#!/bin/bash

echo "Enabling virtual host"
/usr/sbin/a2enmod alias env expires headers mime proxy rewrite setenvif vhost_alias wsgi
/etc/init.d/apache2 restart

/usr/sbin/a2ensite 25-mf-chsdi3

chown -R www-data /var/www/vhosts/mf-chsdi3/logs
/etc/init.d/apache2 restart


