#!/bin/bash

VERSION=1.0.0

EXCLUDES="--exclude=/var/www/vhosts/mf-chsdi3/logs/* --exclude=/var/www/vhosts/mf-chsdi3/private/chsdi/.git --exclude=/var/www/vhosts/mf-chsdi3/private/snapshots  --exclude=/var/www/vhosts/mf-chsdi3/private/chsdi/apache/tomcat* --exclude=/var/www/vhosts/mf-chsdi3/private/chsdi/apache/mapproxy*  --exclude=*.pyc --exclude=/var/www/vhosts/mf-chsdi3/private/chsdi/print  "


echo $EXCLUDES

cd /

echo "Create chsdi3"

echo tar cvjf ~/mf-chsdi3-${VERSION}.tar.bz2   ${EXCLUDES}   --exclude=/var/www/vhosts/mf-chsdi3/private/chsdi/chsdi/static/doc   /var/www/vhosts/mf-chsdi3/


echo "Doc"

echo tar cvjf ~/mf-chsdi3-doc-${VERSION}.tar.bz2   ${EXCLUDES}      /var/www/vhosts/mf-chsdi3/private/chsdi/chsdi/static/doc

tar cvjf ~/mf-chsdi3-doc-${VERSION}.tar.bz2   ${EXCLUDES}      /var/www/vhosts/mf-chsdi3/private/chsdi/chsdi/static